package(default_visibility = ["//visibility:public"])
load("@python_requirements//:requirements.bzl", "requirement")

py_binary(
    name="main",
    srcs=[
        "main.py"
    ],
    deps=[
        requirement("pygame"),
    ],
)